name: Nx Migration
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Daily at 1 AM

jobs:
  nx-migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gridatek/nx-migrate-action@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}